USE webshop;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) DEFAULT NULL,
    lastname VARCHAR(255) DEFAULT NULL,
    street VARCHAR(255) DEFAULT NULL,
    housenumber VARCHAR(255) DEFAULT NULL,
    city VARCHAR(255) DEFAULT NULL,
    zipcode VARCHAR(255) DEFAULT NULL,
    country VARCHAR(255) DEFAULT NULL,
    profile_image VARCHAR(255) DEFAULT 'profil_icon_w.png',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
